default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['POSTGRESQL_ADDRESS'] %>
  database: <%= ENV['POSTGRESQL_DATABASE'] %>
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>

production: &production
  <<: *default

staging:
  <<: *production

development:
  <<: *default

engageny:
  <<: *default
  database: <%= ENV['ENGAGENY_DATABASE'] %>

test:
  <<: *default

integration:
  <<: *default
