default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

test: &test
  <<: *default
  database: content_test
  host: 127.0.0.1
  username: content_test_user
  password: content

integration:
  <<: *test
  database: content_integration

<% unless ['test', 'integration'].include?(Rails.env) %>

<%= ENV['RAILS_ENV'] %>:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  
<% end %>
