# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
<%= ENV['RAILS_ENV'] %>:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: content_test
  host: 127.0.0.1
  pool: 5
  username: content_test_user
  password: content
